package com.polybot.hft.polymarket.fund.model;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;

/**
 * A trading signal generated by an alpha strategy.
 *
 * Unlike TraderSignal (which mirrors other traders), AlphaSignal represents
 * signals from proprietary strategies like InsiderFollowStrategy.
 *
 * Supports different signal types:
 * - INSIDER: Detected insider/unusual trading activity
 * - CONSENSUS: Smart money consensus signal
 * - EDGE_DECAY: Trader edge decay alert
 * - HIDDEN_ALPHA: Newly discovered promising trader
 */
public record AlphaSignal(
        String signalId,
        SignalSource source,         // Which strategy/detector generated this
        SignalAction action,         // BUY, SELL, or HOLD
        String marketSlug,
        String tokenId,
        String outcome,              // "Yes" or "No"

        // Signal quality
        double confidence,           // 0.0 to 1.0
        double strength,             // Normalized signal strength
        SignalUrgency urgency,       // How quickly we should act

        // Suggested sizing
        BigDecimal suggestedSizeUsd, // Suggested notional size
        double suggestedSizePct,     // As % of fund capital

        // Context
        String reason,               // Human-readable explanation
        Map<String, Object> metadata,// Additional signal-specific data

        // Timing
        Instant detectedAt,
        Instant expiresAt            // Signal validity window
) {

    /**
     * Signal sources - which detection system generated this signal.
     */
    public enum SignalSource {
        INSIDER_DETECTOR,    // From insider_detector.py
        CONSENSUS_ENGINE,    // From consensus.py
        HIDDEN_ALPHA,        // From hidden_alpha.py
        EDGE_DECAY,          // From edge decay alerts
        ML_EDGE_PREDICTOR,   // From ML edge prediction model
        ARBITRAGE,           // From arbitrage detection
        MOMENTUM,            // From momentum signals
        CUSTOM               // Custom strategy signals
    }

    /**
     * Signal action - what the strategy recommends.
     */
    public enum SignalAction {
        BUY,     // Open or increase long position
        SELL,    // Close or reduce position
        HOLD     // Maintain current position (informational)
    }

    /**
     * Signal urgency - how quickly we should act.
     */
    public enum SignalUrgency {
        LOW,      // Can wait for optimal entry
        MEDIUM,   // Should act within minutes
        HIGH,     // Should act immediately
        CRITICAL  // Market-taking priority
    }

    /**
     * Check if this signal is still valid.
     */
    public boolean isValid(Instant now) {
        return expiresAt == null || expiresAt.isAfter(now);
    }

    /**
     * Check if signal meets minimum confidence threshold.
     */
    public boolean meetsConfidenceThreshold(double minConfidence) {
        return confidence >= minConfidence;
    }

    /**
     * Calculate time since detection.
     */
    public long ageSeconds(Instant now) {
        return java.time.Duration.between(detectedAt, now).getSeconds();
    }

    /**
     * Create a builder for easier signal construction.
     */
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String signalId;
        private SignalSource source;
        private SignalAction action;
        private String marketSlug;
        private String tokenId;
        private String outcome;
        private double confidence = 0.5;
        private double strength = 1.0;
        private SignalUrgency urgency = SignalUrgency.MEDIUM;
        private BigDecimal suggestedSizeUsd;
        private double suggestedSizePct = 0.01;
        private String reason;
        private Map<String, Object> metadata = Map.of();
        private Instant detectedAt = Instant.now();
        private Instant expiresAt;

        public Builder signalId(String signalId) {
            this.signalId = signalId;
            return this;
        }

        public Builder source(SignalSource source) {
            this.source = source;
            return this;
        }

        public Builder action(SignalAction action) {
            this.action = action;
            return this;
        }

        public Builder marketSlug(String marketSlug) {
            this.marketSlug = marketSlug;
            return this;
        }

        public Builder tokenId(String tokenId) {
            this.tokenId = tokenId;
            return this;
        }

        public Builder outcome(String outcome) {
            this.outcome = outcome;
            return this;
        }

        public Builder confidence(double confidence) {
            this.confidence = confidence;
            return this;
        }

        public Builder strength(double strength) {
            this.strength = strength;
            return this;
        }

        public Builder urgency(SignalUrgency urgency) {
            this.urgency = urgency;
            return this;
        }

        public Builder suggestedSizeUsd(BigDecimal suggestedSizeUsd) {
            this.suggestedSizeUsd = suggestedSizeUsd;
            return this;
        }

        public Builder suggestedSizePct(double suggestedSizePct) {
            this.suggestedSizePct = suggestedSizePct;
            return this;
        }

        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder detectedAt(Instant detectedAt) {
            this.detectedAt = detectedAt;
            return this;
        }

        public Builder expiresAt(Instant expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        public AlphaSignal build() {
            if (signalId == null) {
                signalId = java.util.UUID.randomUUID().toString();
            }
            return new AlphaSignal(
                    signalId, source, action, marketSlug, tokenId, outcome,
                    confidence, strength, urgency,
                    suggestedSizeUsd, suggestedSizePct,
                    reason, metadata, detectedAt, expiresAt
            );
        }
    }
}
