-- AWARE Alerts Schema
-- Tables for persisting alerts, anomalies, and consensus signals

-- =============================================================================
-- Alerts Table
-- =============================================================================
-- Stores all types of alerts generated by the analytics system

CREATE TABLE IF NOT EXISTS polybot.aware_alerts
(
    id               String,                -- UUID for the alert
    alert_type       String,                -- 'POSITION_ENTRY', 'CONSENSUS', 'EDGE_DECAY', etc.
    severity         String,                -- 'INFO', 'WARNING', 'HIGH', 'CRITICAL'
    source           String,                -- Which job generated this ('hidden_alpha', 'consensus', etc.)

    -- Context
    username         Nullable(String),      -- Trader involved (if applicable)
    market_slug      Nullable(String),      -- Market involved (if applicable)
    index_type       Nullable(String),      -- Index involved (if applicable)

    -- Alert content
    title            String,                -- Short description
    message          String,                -- Detailed message
    metadata         String DEFAULT '{}',   -- JSON blob with extra data

    -- Timing
    created_at       DateTime64(3),         -- When alert was generated
    expires_at       Nullable(DateTime64(3)), -- When alert expires (optional)
    acknowledged_at  Nullable(DateTime64(3)), -- When user acknowledged

    -- Status
    status           String DEFAULT 'ACTIVE', -- 'ACTIVE', 'ACKNOWLEDGED', 'RESOLVED'

    _version         UInt64 DEFAULT toUnixTimestamp64Milli(now64(3))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY (alert_type, created_at, id)
PARTITION BY toYYYYMM(created_at)
SETTINGS index_granularity = 8192;

-- =============================================================================
-- Anomalies Table
-- =============================================================================
-- Stores detected anomalies and gaming attempts

CREATE TABLE IF NOT EXISTS polybot.aware_anomalies
(
    id               String,                -- UUID
    anomaly_type     String,                -- 'WASH_TRADING', 'FRONT_RUNNING', 'GAMING', etc.
    severity         String,                -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'

    -- Trader context
    username         String,
    proxy_address    String,

    -- Detection details
    detection_method String,                -- Which algorithm detected this
    confidence       Float64,               -- 0.0 to 1.0
    evidence         String DEFAULT '{}',   -- JSON with evidence details

    -- Impact
    affected_trades  UInt32,                -- Number of trades involved
    affected_volume  Decimal(18, 6),        -- Volume involved

    -- Timing
    detected_at      DateTime64(3),
    period_start     DateTime64(3),         -- Start of anomalous period
    period_end       DateTime64(3),         -- End of anomalous period

    -- Resolution
    status           String DEFAULT 'OPEN', -- 'OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'
    resolution_note  Nullable(String),
    resolved_at      Nullable(DateTime64(3)),

    _version         UInt64 DEFAULT toUnixTimestamp64Milli(now64(3))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY (username, detected_at, id)
PARTITION BY toYYYYMM(detected_at)
SETTINGS index_granularity = 8192;

-- =============================================================================
-- Consensus Signals Table
-- =============================================================================
-- Stores detected consensus signals (when smart money agrees)

CREATE TABLE IF NOT EXISTS polybot.aware_consensus_signals
(
    id               String,                -- UUID
    market_slug      String,
    condition_id     String,

    -- Consensus details
    signal_type      String,                -- 'STRONG_YES', 'STRONG_NO', 'BUILDING', 'SPLIT'
    strength         String,                -- 'WEAK', 'MODERATE', 'STRONG', 'EXTREME'
    direction        String,                -- 'YES', 'NO', 'NEUTRAL'

    -- Metrics
    yes_weight       Float64,               -- Total weight on YES side
    no_weight        Float64,               -- Total weight on NO side
    num_traders      UInt32,                -- Number of smart traders with positions
    agreement_pct    Float64,               -- Percentage agreement (0-100)

    -- Market context
    current_price    Decimal(10, 6),        -- Price when detected
    volume_24h       Decimal(18, 6),        -- 24h volume

    -- Timing
    detected_at      DateTime64(3),
    valid_until      DateTime64(3),         -- When signal expires

    _version         UInt64 DEFAULT toUnixTimestamp64Milli(now64(3))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY (market_slug, detected_at, id)
PARTITION BY toYYYYMM(detected_at)
SETTINGS index_granularity = 8192;

-- =============================================================================
-- Edge Decay Alerts Table
-- =============================================================================
-- Tracks when traders show performance decline

CREATE TABLE IF NOT EXISTS polybot.aware_edge_decay_alerts
(
    id               String,                -- UUID
    username         String,

    -- Decay metrics
    decay_type       String,                -- 'PERFORMANCE', 'WIN_RATE', 'SHARPE', 'STRATEGY_DRIFT'
    signal           String,                -- 'EARLY_WARNING', 'CONFIRMED', 'SEVERE'

    -- Performance comparison
    historical_sharpe    Float64,           -- Past Sharpe ratio
    current_sharpe       Float64,           -- Recent Sharpe ratio
    sharpe_decline_pct   Float64,           -- Percentage decline

    historical_win_rate  Float64,
    current_win_rate     Float64,
    win_rate_decline_pct Float64,

    -- Index impact
    index_type       Nullable(String),      -- If in an index
    weight_in_index  Float64,               -- Current weight
    recommended_action String,              -- 'MONITOR', 'REDUCE_WEIGHT', 'REMOVE'

    -- Timing
    detected_at      DateTime64(3),
    lookback_days    UInt32,                -- How far back we looked

    _version         UInt64 DEFAULT toUnixTimestamp64Milli(now64(3))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY (username, detected_at, id)
PARTITION BY toYYYYMM(detected_at)
SETTINGS index_granularity = 8192;

-- =============================================================================
-- Hidden Alpha Discoveries Table
-- =============================================================================
-- Tracks newly discovered promising traders

CREATE TABLE IF NOT EXISTS polybot.aware_hidden_alpha
(
    id               String,                -- UUID
    username         String,
    proxy_address    String,

    -- Discovery details
    discovery_type   String,                -- 'HIDDEN_GEM', 'RISING_STAR', 'NICHE_SPECIALIST', 'CONTRARIAN'
    discovery_score  Float64,               -- 0-100 discovery score

    -- Why they were discovered
    reason           String,                -- Explanation

    -- Current metrics
    total_pnl        Decimal(18, 6),
    sharpe_ratio     Float64,
    win_rate         Float64,
    total_trades     UInt32,
    days_active      UInt32,

    -- Potential
    upside_estimate  Float64,               -- Estimated upside potential
    risk_level       String,                -- 'LOW', 'MEDIUM', 'HIGH'

    -- Timing
    discovered_at    DateTime64(3),

    _version         UInt64 DEFAULT toUnixTimestamp64Milli(now64(3))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY (discovery_type, discovered_at, username)
PARTITION BY toYYYYMM(discovered_at)
SETTINGS index_granularity = 8192;

-- =============================================================================
-- Views
-- =============================================================================

-- Active alerts (not acknowledged)
CREATE VIEW IF NOT EXISTS polybot.v_active_alerts AS
SELECT *
FROM polybot.aware_alerts FINAL
WHERE status = 'ACTIVE'
ORDER BY severity DESC, created_at DESC;

-- Recent anomalies
CREATE VIEW IF NOT EXISTS polybot.v_recent_anomalies AS
SELECT *
FROM polybot.aware_anomalies FINAL
WHERE status IN ('OPEN', 'INVESTIGATING')
ORDER BY severity DESC, detected_at DESC;

-- Strong consensus signals
CREATE VIEW IF NOT EXISTS polybot.v_strong_consensus AS
SELECT *
FROM polybot.aware_consensus_signals FINAL
WHERE strength IN ('STRONG', 'EXTREME')
  AND valid_until > now64(3)
ORDER BY agreement_pct DESC;

-- Latest hidden alpha discoveries
CREATE VIEW IF NOT EXISTS polybot.v_latest_discoveries AS
SELECT *
FROM polybot.aware_hidden_alpha FINAL
WHERE discovered_at > now64(3) - INTERVAL 7 DAY
ORDER BY discovery_score DESC
LIMIT 50;
